# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.5
_src_path: https://github.com/jupyterlab/extension-template
author_email: axle@axleinfo.com
author_name: axle
has_binder: true
has_settings: true
kind: server
labextension_name: jupy_latex
project_short_description: A JupyterLab extension.
python_name: jupy_latex
repository: ''
test: false

