#!/usr/bin/env bash
python -m pip install .
RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:tectonic-typesetting/tectonic && \
    apt-get install -y tectonic